version: '3.9'
services:
  MQTT_Server:
    image: eclipse-mosquitto:2
    container_name: MQTT_SERVER
    expose:
      - "1883"
      - "9001"
    network_mode: "host"
    entrypoint: mosquitto -c /mosquitto-no-auth.conf  
  
  